name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clone the repo to the runner

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Install Terraform

      - name: Initialize Terraform
        run: terraform init  # Initialize Terraform

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t my-app .  # Replace 'my-app' with your image name
          docker tag my-app:latest <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/my-app:latest

      - name: Push Docker Image to AWS ECR
        run: |
          docker push <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/my-app:latest  # Push the image to ECR

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve  # Deploy changes to AWS
