name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clone the repo to the runner

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Install Terraform

      - name: Initialize Terraform
        run: terraform init  # Initialize Terraform

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 753392824297.dkr.ecr.us-west-2.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t hello-world-repo .  
          docker tag hello-world-repo:latest 753392824297.dkr.ecr.us-west-2.amazonaws.com/hello-world-repo:latest

      - name: Push Docker Image to AWS ECR
        run: |
          docker push 753392824297.dkr.ecr.us-west-2.amazonaws.com/hello-world-repo:latest

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve  # Deploy changes to AWS
